# Generated by Django 3.1.6 on 2021-02-18 08:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptObjID', models.UUIDField(default=uuid.uuid4, help_text='unique Departments objectid for each department registered in the organization', primary_key=True, serialize=False)),
                ('deptID', models.SmallIntegerField(help_text='unique Departments id for each department registered in the organization', unique=True)),
                ('deptName', models.CharField(help_text='Department Nmae For Each Department registered in the Organaization', max_length=50)),
                ('deptLocation', models.CharField(help_text='Department Location For Each Department Regissteredin the Organization', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('jobCatObjID', models.UUIDField(default=uuid.uuid4, help_text='unique job category Id registered in the organization', primary_key=True, serialize=False)),
                ('jobCatID', models.SmallIntegerField(help_text='unique job category Id registered in the organization', unique=True)),
                ('jobCatName', models.CharField(help_text='Job category name for the job registered in the organization', max_length=100, unique=True)),
                ('jobCatDesc', models.CharField(help_text='job category description for category registered in the organization', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillobjID', models.UUIDField(default=uuid.uuid4, help_text='unique sill id registered in the organization', primary_key=True, serialize=False)),
                ('skillID', models.SmallIntegerField(help_text='unique sill id registered in the organization', unique=True)),
                ('skillName', models.CharField(help_text='skill name for registered in the organization', max_length=50, unique=True)),
                ('sillDesc', models.CharField(help_text='skill description registered in the organization', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologyName', models.CharField(help_text='technologies names that are identified by the organizations', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empObjID', models.UUIDField(default=uuid.uuid4, help_text='Unique Employeee ID for Each employee Registered in the company', primary_key=True, serialize=False)),
                ('empID', models.SmallIntegerField(help_text='Unique Employeee ID for Each employee Registered in the company', unique=True)),
                ('empName', models.CharField(help_text='Employee Name For Each employee in the department', max_length=50)),
                ('empJob', models.CharField(choices=[('P', 'President'), ('M', 'Manager'), ('A', 'Analyst'), ('s', 'Salesman'), ('C', 'Clerk')], default='s', help_text='Employee Designation for the each employee Registered in the company', max_length=1)),
                ('hireDate', models.DateField()),
                ('empSal', models.DecimalField(decimal_places=2, help_text='Employee fixed salary for the each emoloyee registered in the organisation', max_digits=8)),
                ('empComm', models.DecimalField(blank=True, decimal_places=2, help_text='Employee fixed Commission for the each employee registered in the organisation', max_digits=8, null=True)),
                ('empDeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmscatalog.departments', to_field='deptID')),
                ('empJobCatID', models.ForeignKey(blank=True, help_text='Employees working job category Id for each employee registered in the organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrmscatalog.jobcategories', to_field='jobCatID')),
                ('empMgrID', models.ForeignKey(blank=True, help_text='Employees Manager ID for each employee registered in the orgaization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrmscatalog.employees', to_field='empID')),
                ('empSkillID', models.ForeignKey(blank=True, help_text='employees Area of main skill for each employee registered in the organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrmscatalog.skills', to_field='skillID')),
                ('empTechnologies', models.ManyToManyField(help_text='select the required tehnologies, hold ctrl key to select the multiple technologies for employee', to='hrmscatalog.Technologies')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDeputations',
            fields=[
                ('deputobjID', models.UUIDField(default=uuid.uuid4, help_text='unique deputaion ID allocated for each deputation executed upon the employee', primary_key=True, serialize=False)),
                ('deputID', models.SmallIntegerField(help_text='unique deputaion ID allocated for each deputation executed upon the employee', unique=True)),
                ('deputBeignDate', models.DateField(help_text='employee deputation begin date for the employeee registerred in the organization')),
                ('deputPeriod', models.IntegerField(help_text='employee deputaion period in months to the organization')),
                ('deputEndDate', models.DateField(blank=True, help_text='employee deputation end date for the employeee registerred in the organization', null=True)),
                ('deputStatus', models.CharField(help_text='deputation status of the employee whether A : active, D : Deactive', max_length=1)),
                ('deputCity', models.CharField(help_text='deputation city name of the employee where he is deputed', max_length=100)),
                ('deputEmpID', models.ForeignKey(help_text='employee id who is on or sent for deputation', on_delete=django.db.models.deletion.CASCADE, to='hrmscatalog.employees', to_field='empID')),
            ],
        ),
    ]
